### ISSUE TITLE
Switch to simple-get?

### ISSUE THREAD

**Issue by tunnckoCore** [doowb/npm-api#1]
I'm seeing that you are using both callback and stream api of the `request` and maybe because of that you are using it. Because of these needs and needs of `github-base`, before some time I created small wrappers around `simple-get`. One is `request-all`, another is `simple-get-stream`.
Both plays well and can works exactly as `request`, but with a smaller codebase.

Let me brief.

Example showing how can be done

``` js
var handle = require('handle-arguments')
var request = require('request-all')(require('simple-get'))
request.stream = require('simple-get-stream')

function req (url, opts, cb) {
  var argz = handle(arguments)
  if (argz.callback) {
    return request.requestAll.apply(this, arguments)
  }
  return request.stream.apply(this, argz.args)
}

// callback
req('https://httpbin.org/ip', function (err, body, res) {
  console.log(err, body) // => {origin: '85.12.234.22'}
})

// options passed to simple-get
// and in addition have `json:true` by default
req('https://httpbin.org/ip', {json: false}, function (err, body, res) {
  console.log(err, body.toString('utf8')) // => '{origin: '85.12.234.22'}'
})

// stream
req('https://httpbin.org/ip')
.pipe(process.stdout) // => {origin: '85.12.234.22'}
```

If you look closely in their repos, you'll see that they are not so big deal and they almost don't have deps. Actually, deps that in anyway you have here - `through2` is the one, another is the `simple-get`.

Request-All uses and acts (almost *) like a `simple-get.concat`, it also handle JSON and perform multiple requests if needed. In same time, it won't do unnecessary calls if don't have link header - it will be as single `.concat` call.

_\* almost_: I'm saying almost, because only the incoming signature is the same, callback arguments are reversed it would be `callback(err, body, response)` instead of `callback(err, response, body)` - i'm considering to follow `simple-get` and `request`, i thought it is better to save it this way, because `simple-get@1` was with it.

And finally, you may ask what is `handle-arguments` and why to use it. It's pretty simple and small thing which (just uses `sliced`) removes the repeating need of getting last argument and doing things like

``` js
var args = [].slice.call(arguments)
var last = args[args.length - 1]
var callback = typeof last === 'function' ? last : false
```

Why we should do it every time everywhere? It's simple as `argz = handle(arguments); if (argz.cb)` - it will have (and will do the type check) correct callback function if it has, otherwise will be undefined.
# 

In the context of this repo, the [lib/list.js#L30-L39](https://github.com/doowb/npm-info/blob/master/lib/list.js#L30-L39) ~~would be simplified to `utils.request(this.url(params), cb)`~~ (not exactly), in one hand.

And in another hand, won't need to change anything other if we manually create `utils.request` method like

``` js
// adding to the requires
require('handle-arguments', 'handle');
require('request-all');
require('simple-get');
require('simple-get-stream');

utils.request = function request(url, opts, cb) {
  var argz = utils.handle(arguments);
  if (argz.callback) {
    var simpleGet = utils.requestAll(utils.simpleGet);
    return simpleGet.requestAll.apply(this, arguments);
  }
  return utils.simpleGetStream.apply(this, argz.args);
};
```

I can PR.

Cheers.

edit: i'll add lazy-cache to them soon, so it will be better.

**Comment by jonschlinkert** [comment]
> what is handle-arguments and why to use it

I know we do `[].slice.call(arguments)` sometimes, but because of [arguments leaks](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments) we really should only do it when it's convenience outweighs other options.

**Comment by tunnckoCore** [comment]
Agree. But this not change the fact that it saves writing time.

And yes, initially `handle-arguments` was using `manage-arguments` which is direct copy of the suggested code by Petka, but switched to `sliced` because it is a bit faster and seems to do the job without leaks.

**Comment by doowb** [comment]
Thanks for the details. Wait to do a PR because I'm still working on the structure and logic here before optimizing the fetching of data.

I'd use `simple-get` and `simple-get-stream` directly in the places they make sense instead of doing the arguments juggling.

**Comment by jonschlinkert** [comment]
> But this not change the fact that it saves writing time and helps a bit for optional arguments.

good grief, sorry I don't want to debate this trivial stuff. IMO it's unnecessary, `[].slice.call(arguments)` is less code than the actual require statement for your lib lol.

**Comment by tunnckoCore** [comment]
> directly in the places they make sense

More work and repeating code for nothing, it not worth, because basically you will do the same thing, but okey. Above example only pluses, haha.

> is less code than

haha :+1: yea, even more if we remove `[].slice.call(arguments)`, haha.

**Comment by jonschlinkert** [comment]
lol true, true
