### ISSUE TITLE
Update paged-request to latest version to fix axios vulnerability

### ISSUE THREAD

**Issue by akedalat** [doowb/npm-api#18]
Hi @doowb Thanks for updating the paged-request
Could you also please update this package as [yeoman-environment ](https://github.com/yeoman/environment) relies on npm-api 🙏

https://npmjs.com/advisories/1594

Many thanks

**Comment by doowb** [comment]
`paged-request` and `npm-api` have recently been published as patched versions, which means that npm will resolve to the latest patch, so there won't be any issues.

If you're still getting the warnings, you probably need to clear your package lock file and npm cache and re-install. Take  a look at [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) for more information.
