### ISSUE TITLE
api

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/npm-api#2]
Would you be opposed to changing the API here to be more similar to yarn-api? Then we can publish another lib with the download methods? Or add the downloads here for backward compatibility.

**Comment by doowb** [comment]
This is for interacting with the NPM's web api via their CouchDb endpoints. It also has a builtin plugin for getting download counts for repositories. It's similar to `github-base` (which I had named this `npm-base` originally but someone else happened to publish that a few days before I published this.

I guess we can modify it so it handles both the web api and the cli commands. I'm assuming that you want to change this so the methods can be extracted from `base-npm` into a module that's not specific to `base`?

I don't really care either way, I just don't want to think of a new name for this ;)

**Comment by jonschlinkert** [comment]
nvm, sorry the last time I looked all of the dependents were ours, now there are a few more. closing
