### ISSUE TITLE
Remove `request`

### ISSUE THREAD

**Issue by doowb** [doowb/npm-api#5]
`request` could be removed since this module doesn't need the flexibility for the entire `request` module.

This module still needs to handle streaming the response so I've considered figuring out a way to use `http(s)` directly or something like `superagent`.

**Comment by Hypnosphi** [comment]
`request` package is now [deprecated](https://github.com/request/request/issues/3142). @doowb would a PR moving this to `http(s)` module be welcome?

**Comment by doowb** [comment]
Yes, that would be great!

I'm not sure why I closed this issue since `request` is still being used.

**Comment by Hypnosphi** [comment]
UPD: I think I'll use `node-fetch` for non-streamed requests and `https` for streamed ones

**Comment by Hypnosphi** [comment]
Unfortunately, I can't check that `view.query()` still works until https://github.com/doowb/npm-api/issues/13 is fixed

**Comment by doowb** [comment]
No problem. NPM changed some things and I'm not sure if the CouchDB API that `view` and `list` use is available anymore.
As long as the package related methods work, that works for me... I need to get unit tests in here and make some other updates anyway.
