### ISSUE TITLE
Cannot find module 'base-plugins'

### ISSUE THREAD

**Issue by arthurvasconcelos** [doowb/npm-api#6]
![image](https://user-images.githubusercontent.com/1286768/49250347-bac0a000-f405-11e8-985c-2c43b0738287.png)

**Comment by doowb** [comment]
It looks like you're using webpack. Until I update this package, use [unlazy-loader](https://github.com/doowb/unlazy-loader) in your webpack config.

**Comment by doowb** [comment]
As of version `1.0.0`, this library no longer uses `lazy-cache` so this error should not occur.
